export const GET_CONTACTS = "GET_CONTACTS";

export const DELETE_CONTACTS = "DELETECONTACTS";

export const ADD_CONTACTS = "ADD_CONTACTS";

export const GET_CONTACT = "GET_CONTACT ";

export const UPDATE_CONTACT = "UPDATE_CONTACT";

export const TOGGLE_COMPLETED = "TOGGLE_COMPLETED";
